In [9]:
from pathlib import Path
import pandas as pd

In [10]:
# parquet_path = "/home/jetson/notebooks/notebooks/dataset/dataset_gimmick_parking/dataset_v1.parquet"
parquet_path = "/home/jetson/notebooks/notebooks/detect/dataset_gimmick_env/dataset_v1.parquet"

In [11]:
df = pd.read_parquet(parquet_path)

In [12]:
df

,出力先パス,入力画像パス,InX,InY,InFrameNum,環境カテゴリ,UTCタイムスタンプ
0,detect/dataset_gimmick_env/ROAD/fb335126-b061-...,camera/eval_gimmick_202510221123_cam1/xy/0_0_0...,0,0,399,ROAD,2025-10-23T22:45:32.129168+00:00
1,detect/dataset_gimmick_env/GATE_RIGHT/192a85a0...,camera/eval_gimmick_202510221123_cam1/xy/0_0_0...,0,0,405,GATE_RIGHT,2025-10-23T22:46:22.408497+00:00
2,detect/dataset_gimmick_env/GATE_RIGHT/1da563de...,camera/eval_gimmick_202510221123_cam1/xy/0_0_0...,0,0,407,GATE_RIGHT,2025-10-23T22:46:29.924131+00:00
3,detect/dataset_gimmick_env/GATE_RIGHT/1f90d502...,camera/eval_gimmick_202510221123_cam1/xy/0_0_0...,0,0,409,GATE_RIGHT,2025-10-23T22:46:33.144791+00:00
4,detect/dataset_gimmick_env/GATE_RIGHT/20ebf1c0...,camera/eval_gimmick_202510221123_cam1/xy/0_0_0...,0,0,411,GATE_RIGHT,2025-10-23T22:46:35.419731+00:00
...,...,...,...,...,...,...,...
371,detect/dataset_gimmick_env/PARKING/83d170e2-b0...,camera/eval_gimmick_parking_202510231710/xy/0_...,0,0,5,PARKING,2025-10-24T03:14:12.721869+00:00
372,detect/dataset_gimmick_env/START_3/8b3a1adc-b0...,camera/eval_gimmick_parking_202510231710/xy/0_...,0,0,7,START_3,2025-10-24T03:14:25.151761+00:00
373,detect/dataset_gimmick_env/START_3/9171fcc6-b0...,camera/eval_gimmick_parking_202510231710/xy/0_...,0,0,9,START_3,2025-10-24T03:14:35.584372+00:00
374,detect/dataset_gimmick_env/START_3/a44e0ad8-b0...,camera/eval_gimmick_parking_202510231710/xy/0_...,0,0,239,START_3,2025-10-24T03:15:07.225423+00:00
375,detect/dataset_gimmick_env/START_3/b4311760-b0...,camera/eval_gimmick_parking_202510231710/xy/0_...,0,0,391,START_3,2025-10-24T03:15:33.879220+00:00

## 除外

In [20]:
# delete = [
#     "0_112_299e4142-af4f-11f0-951f-53adccf0eecb.jpg",
#     "0_56_39924ec2-af4f-11f0-951f-53adccf0eecb.jpg",
#     "0_56_3e4a0acc-af4f-11f0-951f-53adccf0eecb.jpg",
#     "0_84_52d440ca-af4f-11f0-951f-53adccf0eecb.jpg",
#     "0_112_5a5b05b8-af4f-11f0-951f-53adccf0eecb.jpg",
#     "0_82_6010dc30-af4f-11f0-951f-53adccf0eecb.jpg",
#     "0_86_64543a44-af4f-11f0-951f-53adccf0eecb.jpg",
#     "0_103_7f7e534a-af4f-11f0-951f-53adccf0eecb.jpg",
#     "0_127_86e5ad2c-af4f-11f0-951f-53adccf0eecb.jpg",
#     "0_83_a1c67996-af4f-11f0-951f-53adccf0eecb.jpg",
#     "0_85_a5663aaa-af4f-11f0-951f-53adccf0eecb.jpg",
#     "0_83_a79dc6e4-af4f-11f0-951f-53adccf0eecb.jpg",
#     "0_83_aa8af73c-af4f-11f0-951f-53adccf0eecb.jpg",
#     "0_112_aea1b4d2-af4f-11f0-951f-53adccf0eecb.jpg",
#     "0_113_b2a706cc-af4f-11f0-951f-53adccf0eecb.jpg",
#     "0_140_b54dfade-af4f-11f0-951f-53adccf0eecb.jpg",
#     "0_140_b83d74e0-af4f-11f0-951f-53adccf0eecb.jpg",
# ]
# new_df = df[~df["出力先パス"].map(lambda x: Path(x).name).isin(delete)]
new_df = df[~df["入力画像パス"].map(lambda x: "camera/eval_gimmick_parking_202510231710" in x)]
display(new_df)
# print(new_df["出力先パス"].tolist())

,出力先パス,入力画像パス,InX,InY,InFrameNum,環境カテゴリ,UTCタイムスタンプ
0,detect/dataset_gimmick_env/ROAD/fb335126-b061-...,camera/eval_gimmick_202510221123_cam1/xy/0_0_0...,0,0,399,ROAD,2025-10-23T22:45:32.129168+00:00
1,detect/dataset_gimmick_env/GATE_RIGHT/192a85a0...,camera/eval_gimmick_202510221123_cam1/xy/0_0_0...,0,0,405,GATE_RIGHT,2025-10-23T22:46:22.408497+00:00
2,detect/dataset_gimmick_env/GATE_RIGHT/1da563de...,camera/eval_gimmick_202510221123_cam1/xy/0_0_0...,0,0,407,GATE_RIGHT,2025-10-23T22:46:29.924131+00:00
3,detect/dataset_gimmick_env/GATE_RIGHT/1f90d502...,camera/eval_gimmick_202510221123_cam1/xy/0_0_0...,0,0,409,GATE_RIGHT,2025-10-23T22:46:33.144791+00:00
4,detect/dataset_gimmick_env/GATE_RIGHT/20ebf1c0...,camera/eval_gimmick_202510221123_cam1/xy/0_0_0...,0,0,411,GATE_RIGHT,2025-10-23T22:46:35.419731+00:00
...,...,...,...,...,...,...,...
366,detect/dataset_gimmick_env/GATE_CENTER/f210eae...,camera/eval_gimmick_202510231644_cam1/xy/0_0_0...,0,0,1207,GATE_CENTER,2025-10-24T03:10:08.190287+00:00
367,detect/dataset_gimmick_env/GATE_CENTER/01a07bf...,camera/eval_gimmick_202510231644_cam1/xy/0_0_0...,0,0,1299,GATE_CENTER,2025-10-24T03:10:34.296701+00:00
368,detect/dataset_gimmick_env/GATE_CENTER/0c675c7...,camera/eval_gimmick_202510231644_cam1/xy/0_0_0...,0,0,1331,GATE_CENTER,2025-10-24T03:10:52.377355+00:00
369,detect/dataset_gimmick_env/ROAD/195a4e78-b087-...,camera/eval_gimmick_202510231644_cam1/xy/0_0_0...,0,0,1401,ROAD,2025-10-24T03:11:14.103551+00:00
370,detect/dataset_gimmick_env/ROAD/209e824e-b087-...,camera/eval_gimmick_202510231644_cam1/xy/0_0_0...,0,0,1473,ROAD,2025-10-24T03:11:26.293362+00:00

In [21]:
# new_df.to_parquet(parquet_path)

## ソート

In [7]:
new_df = df.sort_values(by=["入力画像パス", "InFrameNum", "値種別"])
new_df

KeyError: '値種別'

In [ ]:
# new_df.to_parquet(parquet_path)

## ユニーク値

In [13]:
from pathlib import Path

pd.unique(df["入力画像パス"].map(lambda x: Path(x).parts[:2]))

array([('camera', 'eval_gimmick_202510221123_cam1')], dtype=object)